# Generated by Django 5.1.4 on 2025-02-11 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('name',
                 models.CharField(max_length=255,
                                  verbose_name='Название категории')),
                ('description',
                 models.TextField(blank=True,
                                  null=True,
                                  verbose_name='Описание категории')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name':
                'category',
                'verbose_name_plural':
                'categories',
                'ordering': ['name'],
                'indexes': [
                    models.Index(fields=['name'],
                                 name='product_cat_name_4f76a1_idx')
                ],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('name',
                 models.CharField(max_length=255,
                                  verbose_name='Название товара')),
                ('description',
                 models.TextField(blank=True,
                                  null=True,
                                  verbose_name='Описание товара')),
                ('price',
                 models.DecimalField(decimal_places=2,
                                     max_digits=10,
                                     verbose_name='Цена')),
                ('stock',
                 models.PositiveIntegerField(verbose_name='Кол-во на складе')),
                ('slug', models.SlugField(max_length=200)),
                ('brand',
                 models.CharField(blank=True,
                                  max_length=255,
                                  null=True,
                                  verbose_name='Бренд')),
                ('material',
                 models.CharField(blank=True,
                                  max_length=255,
                                  null=True,
                                  verbose_name='Материал лезвия')),
                ('blade_length',
                 models.DecimalField(blank=True,
                                     decimal_places=2,
                                     max_digits=5,
                                     null=True,
                                     verbose_name='Длина лезвия (см)')),
                ('handle_material',
                 models.CharField(blank=True,
                                  max_length=255,
                                  null=True,
                                  verbose_name='Материал рукоятки')),
                ('weight',
                 models.DecimalField(blank=True,
                                     decimal_places=2,
                                     max_digits=6,
                                     null=True,
                                     verbose_name='Вес (г)')),
                ('created_at',
                 models.DateTimeField(auto_now_add=True,
                                      verbose_name='Дата добавления')),
                ('updated_up',
                 models.DateTimeField(auto_now=True,
                                      verbose_name='Дата изменения')),
                ('available', models.BooleanField(default=True)),
                ('category',
                 models.ForeignKey(
                     blank=True,
                     default=1,
                     null=True,
                     on_delete=django.db.models.deletion.SET_DEFAULT,
                     related_name='products',
                     to='product.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('image',
                 models.ImageField(blank=True,
                                   upload_to='product_images/',
                                   verbose_name='Изображение')),
                ('product',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='images',
                                   to='product.product',
                                   verbose_name='Товар')),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'slug'],
                               name='product_pro_id_b9e5a0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'],
                               name='product_pro_name_b60cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'],
                               name='product_pro_created_22b186_idx'),
        ),
    ]
