# Generated by Django 5.1.4 on 2025-01-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.ImageField(upload_to='media/', verbose_name='Изображение'),
        ),
    ]
