# Generated by Django 5.1.4 on 2025-01-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productimage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.ImageField(upload_to='product_images/', verbose_name='Изображение'),
        ),
    ]
